DYNAMIC ECONOMIC MODELLING, PROBLEM SET 1:  Stylised facts of the business cycle

In [1]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
import warnings
warnings.filterwarnings('ignore')

FIRST TABLE

In [3]:
file1 = pd.read_excel('tab1int.xlsx')
file1.head()

Date  AveW_nom       AveH       CPI  GDP_nom  GNP_nom       H  CD_nom  \
0 1964-01-01  2.503333  38.400000  13.54642  669.822  674.880  54.773  57.995   
1 1964-04-01  2.523333  38.600000  13.56832  678.674  683.549  55.014  59.476   
2 1964-07-01  2.550000  38.533333  13.59898  692.031  697.079  55.368  61.378   
3 1964-10-01  2.563333  38.600000  13.66175  697.319  702.017  55.907  59.377   
4 1965-01-01  2.593333  38.700000  13.70409  717.790  723.225  56.771  64.915   

   CND_nom      GNPL       AveW          GDP          GNP          CD  \
0  148.651  49.23349  18.479667  4944.642201  4981.980479  428.120492   
1  151.455  49.20442  18.597242  5001.901488  5037.830771  438.344615   
2  154.877  49.91681  18.751406  5088.844899  5125.965330  451.342674   
3  155.800  49.90555  18.762848  5104.170403  5138.558384  434.622212   
4  157.760  50.76552  18.923791  5237.779378  5277.439071  473.690701   

           CND          L  
0  1097.345276  55.466667  
1  1116.239888  55.866667  
2  1138.886887  55.700000  
3  1140.410270  55.633333  
4  1151.189171  55.766667

In [4]:
df1 = file1[['GNP', 'CND', 'CD', 'H', 'AveH', 'L', 'GNPL', 'AveW']]
df1.head()

GNP          CND          CD       H       AveH          L  \
0  4981.980479  1097.345276  428.120492  54.773  38.400000  55.466667   
1  5037.830771  1116.239888  438.344615  55.014  38.600000  55.866667   
2  5125.965330  1138.886887  451.342674  55.368  38.533333  55.700000   
3  5138.558384  1140.410270  434.622212  55.907  38.600000  55.633333   
4  5277.439071  1151.189171  473.690701  56.771  38.700000  55.766667   

       GNPL       AveW  
0  49.23349  18.479667  
1  49.20442  18.597242  
2  49.91681  18.751406  
3  49.90555  18.762848  
4  50.76552  18.923791

In [5]:
# The HP filter is applied, and we keep only the cycle component (the element with index 0)
# The '+1' is needed to avoid negative deviations to exactly compensate positive ones, which would lead to a zero division error when computing %sd
for column in df1:
    df1[column] = sm.tsa.filters.hpfilter(x = np.log(df1[column]), lamb = 1600)[0] + 1
df1.head()

GNP       CND        CD         H      AveH         L      GNPL  \
0  0.984986  0.976948  0.969353  0.987215  0.989949  0.996089  0.990962   
1  0.983737  0.984249  0.980232  0.985694  0.996495  1.001144  0.983652   
2  0.988692  0.994578  0.996751  0.986205  0.996124  0.996029  0.991312   
3  0.978787  0.986197  0.946349  0.990014  0.999225  0.992707  0.984394   
4  0.993152  0.985953  1.019859  0.999522  1.003210  0.992985  0.994829   

       AveW  
0  0.994187  
1  0.996737  
2  1.001203  
3  0.998034  
4  1.002810

In [6]:
means = np.array([])
stdevs = np.array([])
for column in df1:
    means = np.append(means, np.mean(df1[column]))
    stdevs = np.append(stdevs, np.std(df1[column]))
means, stdevs

(array([1., 1., 1., 1., 1., 1., 1., 1.]),
 array([0.0166139 , 0.01407354, 0.04406588, 0.01823751, 0.00418307,
        0.00970958, 0.00872474, 0.0104387 ]))

In [7]:
# this is the percentage standard deviation column
stdcol = np.abs(stdevs/means*100)
stdcol

array([1.66138969, 1.40735368, 4.40658774, 1.82375098, 0.41830689,
       0.97095765, 0.87247397, 1.04386976])

In [8]:
corrcol = np.array([])
shifts = range(-4, 5)
cdf = pd.DataFrame()
cdf['Shift'] = shifts

In [9]:
# these are the others column
for column in df1:
    corrcol = np.array([])
    for shift in shifts:
        corrcol = np.append(corrcol, df1['GNP'].corr(df1[column].shift(shift)))
    cdf[column] = corrcol
cdf

Shift       GNP       CND        CD         H      AveH         L  \
0     -4  0.298687  0.456917  0.093816  0.597167  0.069405  0.677778   
1     -3  0.512503  0.572980  0.297897  0.732320  0.274080  0.786871   
2     -2  0.721164  0.657159  0.510182  0.810119  0.456395  0.838021   
3     -1  0.885016  0.686465  0.695576  0.820604  0.628622  0.814851   
4      0  1.000000  0.637087  0.860358  0.751220  0.710320  0.706425   
5      1  0.885016  0.508844  0.841592  0.578295  0.643170  0.519870   
6      2  0.721164  0.344794  0.748516  0.369530  0.509945  0.305378   
7      3  0.512503  0.134618  0.619068  0.151870  0.336319  0.097141   
8      4  0.298687 -0.057261  0.464788 -0.039787  0.180052 -0.091891   

       GNPL      AveW  
0 -0.070810 -0.037773  
1  0.114454  0.113725  
2  0.342066  0.264217  
3  0.553482  0.413902  
4  0.754350  0.559265  
5  0.687249  0.599498  
6  0.606651  0.582007  
7  0.462227  0.523827  
8  0.302810  0.426239

TABLE 2

In [10]:
file2 = pd.read_excel('tab2int.xlsx')
file2.head()

Date  C_nom  Y_nom       I_nom     w_nom          N       CPI  \
0 1964-01-01   2093   3508  578.537239  2.503333  38.400000  13.54642   
1 1964-04-01   2127   3543  576.935726  2.523333  38.600000  13.56832   
2 1964-07-01   2166   3600  585.838673  2.550000  38.533333  13.59898   
3 1964-10-01   2172   3614  595.964500  2.563333  38.600000  13.66175   
4 1965-01-01   2221   3710  654.076499  2.593333  38.700000  13.70409   

          A     r_nom             C             Y            I          w  \
0  76.13940  3.500000  15450.576610  25896.140825  4270.775890  18.479667   
1  76.13940  3.500000  15676.222259  26112.296880  4252.079300  18.597242   
2  76.13940  3.500000  15927.665163  26472.573678  4307.960402  18.751406   
3  76.13940  3.706667  15898.402474  26453.419218  4362.285211  18.762848   
4  77.33726  4.000000  16206.840440  27072.209829  4772.856125  18.923791   

          Y_N       inf         r  
0  674.378667  0.411239  3.088761  
1  676.484375  0.161666  3.338334  
2  687.004507  0.225968  3.274032  
3  685.321741  0.461579  3.245088  
4  699.540306  0.309916  3.690084

In [11]:
df2 = file2[['Y', 'C', 'I', 'N', 'Y_N', 'w', 'r', 'A']]
df2.head()

Y             C            I          N         Y_N          w  \
0  25896.140825  15450.576610  4270.775890  38.400000  674.378667  18.479667   
1  26112.296880  15676.222259  4252.079300  38.600000  676.484375  18.597242   
2  26472.573678  15927.665163  4307.960402  38.533333  687.004507  18.751406   
3  26453.419218  15898.402474  4362.285211  38.600000  685.321741  18.762848   
4  27072.209829  16206.840440  4772.856125  38.700000  699.540306  18.923791   

          r         A  
0  3.088761  76.13940  
1  3.338334  76.13940  
2  3.274032  76.13940  
3  3.245088  76.13940  
4  3.690084  77.33726

In [12]:
# log transformations
# since it is impossible to apply log to interest rate in a consistent way, we add 100 to r. This means the new variable is (the log of) the capitalization rate
for column in df2:
    if column == 'r':
        df2[column] = np.log(df2[column] + 100)
    else:
        df2[column] = np.log(df2[column])
df2.head()

Y         C         I         N       Y_N         w         r  \
0  10.161849  9.645402  8.359551  3.648057  6.513792  2.916671  4.635590   
1  10.170162  9.659900  8.355163  3.653252  6.516909  2.923013  4.638008   
2  10.183865  9.675813  8.368220  3.651524  6.532341  2.931269  4.637386   
3  10.183141  9.673974  8.380751  3.653252  6.529888  2.931879  4.637106   
4  10.206263  9.693189  8.470700  3.655840  6.550423  2.940420  4.641406   

          A  
0  4.332566  
1  4.332566  
2  4.332566  
3  4.332566  
4  4.348176

In [13]:
# we HP filter like in table 1
for column in df2:
    df2[column] = sm.tsa.filters.hpfilter(x = df2[column], lamb = 1600)[0] + 1
df2.head()

Y         C         I         N       Y_N         w         r  \
0  0.986266  0.984226  0.961358  0.989949  0.996317  0.994187  0.998516   
1  0.984953  0.990015  0.946108  0.996495  0.988457  0.996737  1.000513   
2  0.989039  0.997228  0.948326  0.996124  0.992915  1.001203  0.999471   
3  0.978724  0.986715  0.950102  0.999225  0.979499  0.998034  0.998773   
4  0.992308  0.997300  1.029467  1.003210  0.989098  1.002810  1.002658   

          A  
0  0.996617  
1  0.994541  
2  0.992467  
3  0.990401  
4  1.003963

In [14]:
# computed some of the column, plus an intermediate variable
stdevs2 = np.array([])
rstdevs2 = np.array([])
autocorr = np.array([])
ycorr = np.array([])
means2 = np.array([])
for column in df2:
    means2 = np.append(means2, np.mean(df2[column]))
    stdevs2 = np.append(stdevs2, np.std(df2[column]))
    autocorr = np.append(autocorr, df2[column].autocorr(1))
    ycorr = np.append(ycorr, df2['Y'].corr(df2[column]))
stdevs2, rstdevs2, autocorr, ycorr, means2

(array([0.01683837, 0.01410187, 0.06610655, 0.00418307, 0.01420597,
        0.0104387 , 0.00883673, 0.00718292]),
 array([], dtype=float64),
 array([0.88783521, 0.88786648, 0.85595845, 0.78304276, 0.87554795,
        0.89146241, 0.79880955, 0.70971224]),
 array([1.        , 0.92322499, 0.87838379, 0.70432283, 0.97790918,
        0.55574848, 0.11097151, 0.71322712]),
 array([1., 1., 1., 1., 1., 1., 1., 1.]))

In [15]:
# %sd column
pctstd = stdevs2/means2*100
pctstd

array([1.68383747, 1.41018658, 6.61065495, 0.41830689, 1.42059652,
       1.04386976, 0.88367259, 0.71829191])

In [16]:
# relative sd column
for column in df2:
        rstdevs2 = pctstd / pctstd[0]
rstdevs2

array([1.        , 0.83748379, 3.92594599, 0.24842474, 0.84366606,
       0.61993499, 0.52479685, 0.42658031])

In [17]:
# complete table
sdf = pd.DataFrame({'variable': df2.columns, 'stdev': stdevs2, 'pctstd': pctstd, 'relstdev': rstdevs2, 'autocorr': autocorr, 'ycoor': ycorr})
sdf

variable     stdev    pctstd  relstdev  autocorr     ycoor
0        Y  0.016838  1.683837  1.000000  0.887835  1.000000
1        C  0.014102  1.410187  0.837484  0.887866  0.923225
2        I  0.066107  6.610655  3.925946  0.855958  0.878384
3        N  0.004183  0.418307  0.248425  0.783043  0.704323
4      Y_N  0.014206  1.420597  0.843666  0.875548  0.977909
5        w  0.010439  1.043870  0.619935  0.891462  0.555748
6        r  0.008837  0.883673  0.524797  0.798810  0.110972
7        A  0.007183  0.718292  0.426580  0.709712  0.713227